module.exports = {
  preset: 'jest-expo',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
  },
  testMatch: ['**/tests/unit/**/*.test.{js,jsx,ts,tsx}'],
  maxWorkers: process.env.CI ? '100%' : '50%',
  testTimeout: 10000,
  workerIdleMemoryLimit: '512MB',
  clearMocks: true,
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@sentry/react-native|native-base|react-native-svg|@shopify/flash-list)',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.{js,ts}',
    '!src/translations/**/*',
    '!src/assets/**/*',
    '!src/navigation/**/*',
    '!App.tsx',
  ],
  coverageReporters: ['json', 'lcov', 'cobertura', 'text'],
  moduleNameMapper: {
    '^fuse.js/dist/fuse.js$': '<rootDir>/node_modules/fuse.js/dist/fuse.js',
    '^.+\\.html$': '<rootDir>/tests/mocks/deps/html-asset-mock.js',
    '^@assets/(.*)$': '<rootDir>/src/assets/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@context/(.*)$': '<rootDir>/src/context/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@styles/(.*)$': '<rootDir>/src/styles/$1',
    '^@customTypes/(.*)$': '<rootDir>/src/customTypes/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@providers/(.*)$': '<rootDir>/src/providers/$1',
    '^@test-data/(.*)$': '<rootDir>/tests/data/$1',
    '^@data/(.*)$': '<rootDir>/tests/data/$1',
    '^@mocks/(.*)$': '<rootDir>/tests/mocks/$1',
    '^@test-helpers/(.*)$': '<rootDir>/tests/helpers/$1',
    '^@translations/(.*)$': '<rootDir>/src/translations/$1',
    '^@app/(.*)$': '<rootDir>/$1',
    '^expo-font$': '<rootDir>/tests/mocks/deps/expo-font-mock',
    '^@expo/vector-icons$': '<rootDir>/tests/mocks/deps/expo-vector-icons-mock.tsx',
    '^react-native-paper$': '<rootDir>/tests/mocks/deps/react-native-paper-mock.tsx',
    '^react-native-image-crop-picker$':
      '<rootDir>/tests/mocks/deps/react-native-image-crop-picker-mock.tsx',
    '^react-native-copilot$': '<rootDir>/tests/mocks/deps/react-native-copilot-mock.tsx',
    '^react-native-reanimated$': '<rootDir>/tests/mocks/deps/react-native-reanimated-mock.ts',
    '^expo-clipboard$': '<rootDir>/tests/mocks/deps/expo-clipboard-mock.tsx',
    '^react-native-webview$': '<rootDir>/tests/mocks/deps/react-native-webview-mock.tsx',
    '^expo-image-manipulator$': '<rootDir>/tests/mocks/deps/expo-image-manipulator-mock.tsx',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup-community-mocks.js', '<rootDir>/tests/setup.js'],
};
