name: 'Setup iOS Build Environment'
description: 'Setup Python, EAS, CocoaPods caching, and Expo caching for iOS builds'

inputs:
  eas-version:
    description: 'EAS CLI version'
    required: false
    default: 'latest'
  expo-token:
    description: 'Expo token for EAS'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Python for recipe-scraper module
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install Python packages for recipe-scraper
      shell: bash
      run: |
        pip install pytest "recipe-scrapers[online]>=15.0.0"
        python -c "from recipe_scrapers import scrape_me; print('recipe-scrapers OK')"
        python -c "import pytest; print('pytest OK')"

    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Cache Xcode Derived Data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/Podfile.lock', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-xcode-deriveddata-

    - name: Cache global Expo artifacts
      uses: actions/cache@v4
      with:
        path: ~/.expo
        key: ${{ runner.os }}-expo-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-expo-

    - name: Cache Expo prebuild (iOS native)
      uses: actions/cache@v4
      with:
        path: ios
        key: ${{ runner.os }}-expo-prebuild-ios-${{ hashFiles('app.json', 'app.config.ts', 'package-lock.json', 'plugins/**', 'modules/**') }}
        restore-keys: |
          ${{ runner.os }}-expo-prebuild-ios-

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        packager: 'npm'
        token: ${{ inputs.expo-token }}
