name: 'Setup Android Build Environment'
description: 'Setup Java, Python/Chaquopy, Android SDK, Gradle caching, Expo caching, and EAS for Android builds'

inputs:
  eas-version:
    description: 'EAS CLI version'
    required: false
    default: 'latest'
  expo-token:
    description: 'Expo token for EAS'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Python for Chaquopy
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install Python packages for Chaquopy
      shell: bash
      run: |
        pip install pytest "recipe-scrapers[online]>=15.0.0"
        python -c "from recipe_scrapers import scrape_me; print('recipe-scrapers OK')"
        python -c "import pytest; print('pytest OK')"

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle with caching
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: false

    - name: Cache global Expo artifacts
      uses: actions/cache@v4
      with:
        path: ~/.expo
        key: ${{ runner.os }}-expo-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-expo-

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: ${{ inputs.eas-version }}
        packager: 'npm'
        token: ${{ inputs.expo-token }}
