name: 'Setup Maestro Environment'
description: 'Setup Java, Android SDK, Maestro CLI, and KVM for E2E testing'

inputs:
  maestro-version:
    description: 'Maestro CLI version'
    required: false
    default: '2.0.10'
  apk-artifact:
    description: 'Name of the APK artifact to download'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Download APK
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.apk-artifact }}

    - name: Cache Maestro CLI
      uses: actions/cache@v4
      id: maestro-cache
      with:
        path: ~/.maestro
        key: maestro-${{ runner.os }}-${{ inputs.maestro-version }}

    - name: Install Maestro CLI
      if: steps.maestro-cache.outputs.cache-hit != 'true'
      shell: bash
      run: bash .github/scripts/install-maestro.sh ${{ inputs.maestro-version }}

    - name: Add Maestro to PATH
      shell: bash
      run: echo "$HOME/.maestro/bin" >> $GITHUB_PATH

    - name: Verify Maestro installation
      shell: bash
      run: maestro --version || { echo "Maestro installation failed"; exit 1; }

    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
